version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Medal318
      POSTGRES_DB: mi_base_de_datos
    ports:
      - "5432:5432"
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:Medal318@postgres:5432/mi_base_de_datos"
